# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mini-etl-nbdev',
                'doc_host': 'https://akshaysmmoser.github.io',
                'git_url': 'https://github.com/akshaysmmoser/mini-etl-nbdev',
                'lib_path': 'mini_etl_nbdev'},
  'syms': {'mini_etl_nbdev.core': {'mini_etl_nbdev.core.foo': ('core.html#foo', 'mini_etl_nbdev/core.py')}}}
