"""testing the nbdev notebook and commands"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['normalize_text']

# %% ../nbs/00_core.ipynb #b3c5c622
def normalize_text(text: str) -> str:
    "Normalize text by trimming whitespace and lowercasing."
    return text.strip().lower()

