"""Upper Case Function"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_testing.ipynb.

# %% auto #0
__all__ = ['normalize_text_upper']

# %% ../nbs/01_testing.ipynb #4418bcff
def normalize_text_upper(text: str) -> str:
    "Normalize text by trimming whitespace and lowercasing."
    return text.strip().upper()

